server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jsw12321!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


        registration:
          kakao:
            client-id: 0eb8c4ca09a90b72a9614a8addde5dd9
            client-secret: DOnDhXoMFPFeRBMbv8bA9TIu3H4Svq5t
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao